application: fr-testapp
version: v0-003
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheet
  static_dir: stylesheet
  
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /font
  static_dir: font
  
- url: /js
  static_dir: js
  
- url: /js/vendor
  static_dir: js/vendor

- url: /js/fr
  static_dir: js/fr

- url: /flashcanvas
  static_dir: flashcanvas
    
- url: /graphael
  static_dir: graphael
  
- url: /js/vendor/jqplotplugins
  static_dir: js/vendor/jqplotplugins

- url: /staticpages
  static_dir: staticpages
  
- url: /_ah/mail/.+
  script: mailhandler.app
  login: admin

- url: .*
  script: main.app

  
inbound_services:
- mail

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: PIL
  version: latest